# src/main/resources/application.yml
server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    username: postgres
    password: 12345
    url: jdbc:postgresql://postgres:5432/user_service_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis
    time-to-live: 10m

  kafka:
    producer:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    hostname: user-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  server:
    port: 8081
